### ISSUE TITLE
Autogenerated MPC Code segfaults in acado_feedbackStep( ) on large OCP definitions

### ISSUE THREAD

**Issue by AIRCAP** [acado/acado#288]
When trying to formulate a robotic formation controller as an MPC problem, I run into an issue with acado, where the autogenerated code triggers a segmentation fault on "acado_feedbackStep( )"

I first thought I had an error in my problem formulation, so I simplified the problem to get to the simplest possible (although nonsensical) formulation that still triggers the bug.

It seems like any problem with a sufficient number of QP variables and/or constraints triggers this issue, as long as a few trivial side-effect conditions are met.

The problem occurs both with an older ACADO shipped with ROS melodic, as well as latest "stable" and "master" branches from github (latest revision tested: b4e28f3131f79cadfd1a001e9fff061f361d3a0f )

**Steps to reproduce:**
Using this example solver: https://gist.github.com/AIRCAP/e051e3f9bf4710d79209a714ed013967

1.  **Compile solver definition with latest Acado --> yields code generation executable**

2.  **Run code generation executable:**
```
./nmpc_solver_setup

ACADO Toolkit::Code Generation Tool
Copyright (C) 2008-2014 by Boris Houska, Hans Joachim Ferreau,
Milan Vukov, Rien Quirynen, KU Leuven.
Developed within the Optimization in Engineering Center (OPTEC)
under supervision of Moritz Diehl. All rights reserved.

ACADO Toolkit is distributed under the terms of the GNU Lesser
General Public License 3 in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU Lesser General Public License for more details.

[ACADO] Information: ACADO Code Generation Tool:
	* Number of QP variables: 450
	* Number of path and point constraints: 2250
```

3. **Compile code with "make test"**
```
gcc -O3 -finline-functions -I. -I./qpoases   -c -o test.o test.c
g++ -O3 -finline-functions -I. -I./qpoases -I./qpoases/INCLUDE -I./qpoases/SRC   -c -o qpoases/SRC/Bounds.o qpoases/SRC/Bounds.cpp
g++ -O3 -finline-functions -I. -I./qpoases -I./qpoases/INCLUDE -I./qpoases/SRC   -c -o qpoases/SRC/Constraints.o qpoases/SRC/Constraints.cpp
g++ -O3 -finline-functions -I. -I./qpoases -I./qpoases/INCLUDE -I./qpoases/SRC   -c -o qpoases/SRC/CyclingManager.o qpoases/SRC/CyclingManager.cpp
g++ -O3 -finline-functions -I. -I./qpoases -I./qpoases/INCLUDE -I./qpoases/SRC   -c -o qpoases/SRC/Indexlist.o qpoases/SRC/Indexlist.cpp
g++ -O3 -finline-functions -I. -I./qpoases -I./qpoases/INCLUDE -I./qpoases/SRC   -c -o qpoases/SRC/MessageHandling.o qpoases/SRC/MessageHandling.cpp
g++ -O3 -finline-functions -I. -I./qpoases -I./qpoases/INCLUDE -I./qpoases/SRC   -c -o qpoases/SRC/QProblem.o qpoases/SRC/QProblem.cpp
g++ -O3 -finline-functions -I. -I./qpoases -I./qpoases/INCLUDE -I./qpoases/SRC   -c -o qpoases/SRC/QProblemB.o qpoases/SRC/QProblemB.cpp
g++ -O3 -finline-functions -I. -I./qpoases -I./qpoases/INCLUDE -I./qpoases/SRC   -c -o qpoases/SRC/SubjectTo.o qpoases/SRC/SubjectTo.cpp
g++ -O3 -finline-functions -I. -I./qpoases -I./qpoases/INCLUDE -I./qpoases/SRC   -c -o qpoases/SRC/Utils.o qpoases/SRC/Utils.cpp
g++ -O3 -finline-functions -I. -I./qpoases -I./qpoases/INCLUDE -I./qpoases/SRC   -c -o qpoases/SRC/EXTRAS/SolutionAnalysis.o qpoases/SRC/EXTRAS/SolutionAnalysis.cpp
g++ -O3 -finline-functions -I. -I./qpoases -I./qpoases/INCLUDE -I./qpoases/SRC   -c -o acado_qpoases_interface.o acado_qpoases_interface.cpp
gcc -O3 -finline-functions -I. -I./qpoases   -c -o acado_integrator.o acado_integrator.c
gcc -O3 -finline-functions -I. -I./qpoases   -c -o acado_solver.o acado_solver.c
gcc -O3 -finline-functions -I. -I./qpoases   -c -o acado_auxiliary_functions.o acado_auxiliary_functions.c
gcc   test.o qpoases/SRC/Bounds.o qpoases/SRC/Constraints.o qpoases/SRC/CyclingManager.o qpoases/SRC/Indexlist.o qpoases/SRC/MessageHandling.o qpoases/SRC/QProblem.o qpoases/SRC/QProblemB.o qpoases/SRC/SubjectTo.o qpoases/SRC/Utils.o qpoases/SRC/EXTRAS/SolutionAnalysis.o acado_qpoases_interface.o acado_integrator.o acado_solver.o acado_auxiliary_functions.o  -lm -lstdc++ -lrt -o test

```
4. **Run ./test**

**Expected Outcome:**
1. Test runs and displays some statistics/ possible solutions, such as
```
ACADO Toolkit -- A Toolkit for Automatic Control and Dynamic Optimization.
Copyright (C) 2008-2015 by Boris Houska, Hans Joachim Ferreau,
Milan Vukov and Rien Quirynen, KU Leuven.
Developed within the Optimization in Engineering Center (OPTEC) under
supervision of Moritz Diehl. All rights reserved.

ACADO Toolkit is distributed under the terms of the GNU Lesser
General Public License 3 in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU Lesser General Public License for more details.

	Real-Time Iteration 0:  KKT Tolerance = 0.000e+00

...

End of the RTI loop. 



Differential variables:
[
	1.000000e-01	1.000000e-01	1.000000e-01
	1.000000e-01	1.000000e-01	1.000000e-01
...
]


Control variables:
[
	0.000000e+00	0.000000e+00	0.000000e+00
	0.000000e+00	0.000000e+00	0.000000e+00
...
]

```
or
2. Code generation or compilation should abort with an error at generation time, if the problem is too large for ACADO to handle, with a detailed error message why.

**Actual Outcome:**
Test segfaults:
```
ACADO Toolkit -- A Toolkit for Automatic Control and Dynamic Optimization.
Copyright (C) 2008-2015 by Boris Houska, Hans Joachim Ferreau,
Milan Vukov and Rien Quirynen, KU Leuven.
Developed within the Optimization in Engineering Center (OPTEC) under
supervision of Moritz Diehl. All rights reserved.

ACADO Toolkit is distributed under the terms of the GNU Lesser
General Public License 3 in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU Lesser General Public License for more details.

Segmentation fault (core dumped)
```
When compiled with -O0 -g and run in gdb I get the following backtrace:
```
Program received signal SIGSEGV, Segmentation fault.
0x000055555556c95e in acado_solve () at acado_qpoases_interface.cpp:43
43		QProblem qp(450, 2250);
(gdb) bt
#0  0x000055555556c95e in acado_solve () at acado_qpoases_interface.cpp:43
#1  0x00005555555d01d1 in acado_feedbackStep () at acado_solver.c:14918
#2  0x00005555555555f3 in main () at test.c:92
```

**Additional Info:**
Acado Versions tested: ROS melodic 1.2.3,  git stable,  git master
Operating System: Ubuntu 18.04 LTS
Compiler: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0

**Comment by mkyun2** [comment]
i have same problem.
